bind 0.0.0.0
protected-mode no
port 6379
tcp-keepalive 60

save ""
appendonly no
dir /data
logfile ""
loglevel notice

loadmodule /opt/chronicle/chronicle.so

user default on nopass resetkeys resetchannels nocommands ~* +ping +hello +quit +auth +@read +scan +chronicle.new +chronicle.show +chronicle.export +chronicle.import
